### PR TITLE
Add an example of using go-loggly

### PR DESCRIPTION
**Pull request by pwrdwnsys**
Here is a very simple example of using go-loggly.

### CODE REVIEW

**Review by stephenmathieson — CHANGES_REQUESTED** [review]
Please run `gofmt` to cleanup the whitespace here.

**Comment by thapakazi** [comment]
We are also trying to use loggly, this repo seems well perfect help. Can we add more of the example to send the custom json like msg to loggly @pwrdwnsys /cc @stephenmathieson 

Something like
```go
logToLoggly.Info({msg: "A test message from Golang to Loggly!", source: "go_client", url: "https://myapp.com/path" })
```

**Comment by stephenmathieson** [comment]
@thapakazi I'm no longer maintaining this repo (and am now unsubscribed from this thread). Perhaps @stevenmiller888 or @achille-roussel could take a look?

**Comment by achille-roussel** [comment]
The change look fine 👍

**Pull request merged**
